"""Cue sheet for the full-length animatic, cut to "Presentacion_Rehenes.mp3".

    python3 animatic_cues.py /path/to/Presentacion_Rehenes.mp3

Beat grid is measured from the track (librosa). Narration cues come from an
automatic transcription (faster-whisper "medium", word timestamps) of the same
track and are entered here by hand; names are as transcribed and still need to
be confirmed by the band.

Writes ../intro-demo/animatic-cues.js and ../intro-demo/audio/presentacion.wav.
"""
import json
import pathlib
import subprocess
import sys

import imageio_ffmpeg
import librosa
import numpy as np

ROOT = pathlib.Path(__file__).resolve().parent.parent / "intro-demo"

# ---- narration (seconds, from word timestamps) ----------------------------
WORDS = [  # kinetic words in the archive act: [start, text, accent]
    [43.52, "CONTINUIDAD", 0],
    [54.00, "HISTORIA GRUPERA", 0],
    [57.44, "GARANTÍA", 0],
    [58.46, "SELLO DE ÉXITO", 0],
    [60.22, "LOS REHENES", 1],
    [66.65, "LOS REHENES DE JAVIER TORRES", 1],
    [75.49, "AMAN SU MÚSICA", 0],
    [76.85, "DE USTEDES Y PARA USTEDES", 0],
]
MEMBERS = [  # [name spoken at, instrument spoken at, name, instrument]
    [115.08, 116.54, "ALBERTO TAVARES", "TECLADOS"],
    [122.75, 124.19, "ROBERTO HERNÁNDEZ", "PERCUSIONES"],
    [130.90, 132.50, "MIGUEL ÁNGEL LANDEROS", "GUITARRA"],
    [137.35, 139.35, "HÉCTOR ULISES TORRES", "BATERÍA"],
    [144.00, 146.54, "GERARDO TORRES", "BAJO"],
]
LEADER = {"roles": [[153.02, "COMPOSITOR"], [154.44, "DIRECTOR"], [155.62, "LA VOZ"]],
          "name": 158.96, "hit": 159.54, "again": 161.65, "nameText": "JAVIER TORRES"}


def main(src):
    wav = ROOT / "audio" / "presentacion.wav"
    wav.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run([imageio_ffmpeg.get_ffmpeg_exe(), "-y", "-loglevel", "error", "-i", src,
                    "-ar", "48000", "-c:a", "pcm_s24le", str(wav)], check=True)
    y, sr = librosa.load(str(wav), sr=22050, mono=True)
    dur = len(y) / sr
    _, beats = librosa.beat.beat_track(y=y, sr=sr, hop_length=512, start_bpm=99.4)
    bt = librosa.frames_to_time(beats, sr=sr, hop_length=512)

    # archive cuts: every 4th beat from the "play" hit until the map
    play, map_in = 42.49, 79.21
    grid = bt[(bt >= play - 0.05) & (bt < map_in - 1.0)]
    cuts = [round(float(x), 3) for x in grid[::4]]

    cues = {
        "fps": 30, "dur": round(dur, 3),
        "beats": [round(float(x), 3) for x in bt],
        "sky": {"star": 3.74, "tvOn": 27.13},
        "archive": {"play": play, "cuts": cuts, "words": WORDS, "crowd": [74.8, 79.3], "end": map_in},
        "map": {"start": map_in, "title": 79.73, "americas": [81.69, 84.3], "americasLabel": 82.85,
                "europe": [84.63, 86.4], "europeLabel": 84.63, "zoom": [89.4, 91.45]},
        "zac": {"start": 91.45, "ridge": [91.6, 97.6], "state": 96.54, "zacatecas": 99.70,
                "fresnillo": 101.96, "tierra": 103.16, "build": [103.7, 109.3], "off": [109.3, 109.51]},
        "silence": [109.51, 113.58],
        "hoy": [113.58, 115.0],
        "members": MEMBERS, "memberEnds": [122.6, 130.8, 137.25, 143.9, 152.2],
        "leader": LEADER, "leaderEnd": 161.9,
        "logo": {"trace": [161.9, 164.8], "flicker": [[164.82, 164.9], [165.0, 165.06], [165.38, 999]],
                 "ignite": 165.38, "echo": 166.94, "shock": [168.69, 170.79], "fade": [172.9, round(dur, 3)]},
    }
    (ROOT / "animatic-cues.js").write_text(
        "// Generated by tools/animatic_cues.py — cue sheet for the full animatic.\n"
        f"window.CUES = {json.dumps(cues)};\n")
    print(f"dur {dur:.2f}s, {len(bt)} beats, tempo ~{60/np.median(np.diff(bt)):.1f} BPM, {len(cuts)} archive cuts")


if __name__ == "__main__":
    main(sys.argv[1])
