"""Extract the filled vector paths from the source PDF retrace.

The PDF contains an off-page raster scan (reference only), three stray guide
strokes and ten filled paths (yellow silhouette + red outline/inner lines).
We keep only the filled paths, drop the background, and write:
  - ../los-rehenes-logo.svg       clean layered SVG, transparent background
  - ../animation/data.js          layer data + timeline for the animation engine
"""
import json
import pathlib
import pymupdf

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
VIEWBOX = "0 22 782 308"

# PDF drawing index -> layer
LAYERS = {
    "outer": [4, 3],                    # yellow silhouette (+ yellow inside the "o")
    "band":  [9],                       # red outer contour band
    "inner": [8, 5, 6, 7, 10, 11, 12],  # red inner line, E bars, details
}


def num(v):
    return f"{v:.2f}".rstrip("0").rstrip(".")


def pt(q):
    return f"{num(q.x)} {num(q.y)}"


def drawing_to_d(dr):
    out, cur = [], None
    for it in dr["items"]:
        kind = it[0]
        if kind == "re":
            r = it[1]
            out.append(f"M{num(r.x0)} {num(r.y0)}H{num(r.x1)}V{num(r.y1)}H{num(r.x0)}Z")
            cur = None
            continue
        if kind == "qu":
            q = it[1]
            out.append(f"M{pt(q.ul)}L{pt(q.ur)}L{pt(q.lr)}L{pt(q.ll)}Z")
            cur = None
            continue
        a = it[1]
        if cur is None or abs(a.x - cur.x) > 0.01 or abs(a.y - cur.y) > 0.01:
            if out and cur is not None:
                out.append("Z")
            out.append("M" + pt(a))
        if kind == "l":
            out.append("L" + pt(it[2]))
            cur = it[2]
        elif kind == "c":
            out.append(f"C{pt(it[2])} {pt(it[3])} {pt(it[4])}")
            cur = it[4]
    out.append("Z")
    return "".join(out)


def main():
    page = pymupdf.open(ROOT / "source-trazo.pdf")[0]
    drawings = page.get_drawings()
    layers = {}
    for name, idxs in LAYERS.items():
        paths = []
        for i in idxs:
            dr = drawings[i]
            paths.append({
                "d": drawing_to_d(dr),
                "rule": "evenodd" if dr.get("even_odd") else "nonzero",
                "fill": "#%02X%02X%02X" % tuple(round(c * 255) for c in dr["fill"]),
            })
        layers[name] = paths

    timeline = json.loads((HERE / "timeline.json").read_text())
    (ROOT / "animation" / "data.js").write_text(
        "// Generated by tools/extract.py — do not edit by hand.\n"
        f"window.LOGO = {json.dumps({'viewBox': VIEWBOX, 'layers': layers})};\n"
        f"window.TIMELINE = {json.dumps(timeline)};\n")

    groups = []
    for name, paths in layers.items():
        body = "".join(f'<path fill-rule="{p["rule"]}" d="{p["d"]}"/>' for p in paths)
        groups.append(f'  <g id="{name}" fill="{paths[0]["fill"]}">{body}</g>')
    svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{VIEWBOX}" width="1564" height="616">\n'
           f'  <title>Los Rehenes</title>\n' + "\n".join(groups) + "\n</svg>\n")
    (ROOT / "los-rehenes-logo.svg").write_text(svg)


if __name__ == "__main__":
    main()
