"""Build the land outline used by the "route" scene of the intro animatic.

Source: Natural Earth 1:110m land (public domain) via the world-atlas npm package:
    curl -sSfL -o land-110m.json https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/land-110m.json
    python3 map_paths.py land-110m.json

Writes ../intro-demo/map.js with an SVG path (1920x1080 frame, equirectangular,
framed on the Americas + Europe) and the projection constants.
"""
import json
import pathlib
import sys

OUT = pathlib.Path(__file__).resolve().parent.parent / "intro-demo" / "map.js"
PX = 9.5                      # pixels per degree
LON0, LAT0 = -135.0, 66.0     # top-left corner of the frame
X0, Y0 = 105.0, -8.0


def proj(lon, lat):
    return X0 + (lon - LON0) * PX, Y0 + (LAT0 - lat) * PX


def decode_arcs(topo):
    sx, sy = topo["transform"]["scale"]
    tx, ty = topo["transform"]["translate"]
    arcs = []
    for arc in topo["arcs"]:
        x = y = 0
        pts = []
        for dx, dy in arc:
            x += dx
            y += dy
            pts.append((x * sx + tx, y * sy + ty))
        arcs.append(pts)
    return arcs


def ring(arcs, idxs):
    pts = []
    for i in idxs:
        a = arcs[i] if i >= 0 else arcs[~i][::-1]
        pts.extend(a[1:] if pts else a)
    return pts


def main(src):
    topo = json.loads(pathlib.Path(src).read_text())
    arcs = decode_arcs(topo)
    d = []
    for geom in topo["objects"]["land"]["geometries"]:
        polys = geom["arcs"] if geom["type"] == "MultiPolygon" else [geom["arcs"]]
        for poly in polys:
            for r in poly:
                pts = [proj(lon, lat) for lon, lat in ring(arcs, r)]
                xs, ys = [p[0] for p in pts], [p[1] for p in pts]
                if max(xs) < -50 or min(xs) > 1970 or max(ys) < -50 or min(ys) > 1130:
                    continue
                if (max(xs) - min(xs)) < 6 and (max(ys) - min(ys)) < 6:
                    continue          # drop specks
                # break the outline where it jumps across the antimeridian
                seg = [f"M{pts[0][0]:.0f} {pts[0][1]:.0f}"]
                for (x0, _), (x, y) in zip(pts, pts[1:]):
                    seg.append(f"{'M' if abs(x - x0) > 800 else 'L'}{x:.0f} {y:.0f}")
                d.append("".join(seg))
    OUT.write_text("// Generated by tools/map_paths.py (Natural Earth 1:110m land, public domain).\n"
                   f"window.MAP = {json.dumps({'d': ''.join(d), 'px': PX, 'lon0': LON0, 'lat0': LAT0, 'x0': X0, 'y0': Y0})};\n")
    print("wrote", OUT, sum(len(s) for s in d), "chars")


if __name__ == "__main__":
    main(sys.argv[1])
